language: java
cache:
  directories:
  - $HOME/protobuf
sudo: false
before_install:
  - bash install-protobuf.sh
before_script:
  - ls -R $HOME/protobuf
script: mvn package
jdk:
  - oraclejdk8
after_success:
  - mvn clean test -Pall-tests jacoco:report coveralls:report